(function(g){var window=this;var g6=function(a){g.BH.call(this,{I:"div",M:"ytp-miniplayer-ui"});this.player=a;this.K=!1;this.J=this.F=this.C=void 0;this.R(a,"minimized",this.aU);this.R(a,"onStateChange",this.uX)},h6=function(a){g.EU.call(this,a);
this.o=new g6(this.player);this.o.hide();g.uU(this.player,this.o.element,4);a.app.L.o&&(this.load(),g.U(a.getRootNode(),"ytp-player-minimized",!0))};
g.r(g6,g.BH);g.h=g6.prototype;
g.h.show=function(){this.C=new g.ku(this.rQ,null,this);this.C.start();if(!this.K){this.H=new g.OZ(this.player,this);g.N(this,this.H);g.uU(this.player,this.H.element,4);this.H.F=.6;this.P=new g.mZ(this.player);g.N(this,this.P);this.G=new g.W({I:"div",M:"ytp-miniplayer-scrim"});g.N(this,this.G);this.G.wa(this.element);this.R(this.G.element,"click",this.xE);var a=new g.W({I:"button",ea:["ytp-miniplayer-close-button","ytp-button"],U:{"aria-label":"Close"},O:[g.ZU()]});g.N(this,a);a.wa(this.G.element);
this.R(a.element,"click",this.PC);this.D=new g.W({I:"div",M:"ytp-miniplayer-controls"});g.N(this,this.D);this.D.wa(this.G.element);this.R(this.D.element,"click",this.xE);var b=new g.W({I:"div",M:"ytp-miniplayer-button-container"});g.N(this,b);b.wa(this.D.element);a=new g.W({I:"div",M:"ytp-miniplayer-play-button-container"});g.N(this,a);a.wa(this.D.element);var c=new g.W({I:"div",M:"ytp-miniplayer-button-container"});g.N(this,c);c.wa(this.D.element);this.N=new g.mY(this.player,this,!1);g.N(this,this.N);
this.N.wa(b.element);b=new g.kY(this.player,this);g.N(this,b);b.wa(a.element);this.L=new g.mY(this.player,this,!0);g.N(this,this.L);this.L.wa(c.element);this.J=new g.$Y(this.player,this);g.N(this,this.J);this.J.wa(this.G.element);this.F=new g.nY(this.player,this);g.N(this,this.F);g.uU(this.player,this.F.element,4);this.B=new g.W({I:"div",M:"ytp-miniplayer-buttons"});g.N(this,this.B);g.uU(this.player,this.B.element,4);this.B.hide();a=new g.W({I:"button",ea:["ytp-miniplayer-close-button","ytp-button"],
U:{"aria-label":"Close"},O:[g.ZU()]});g.N(this,a);a.wa(this.B.element);this.R(a.element,"click",this.PC);a=new g.W({I:"button",ea:["ytp-miniplayer-replay-button","ytp-button"],U:{"aria-label":"Close"},O:[g.$U()]});g.N(this,a);a.wa(this.B.element);this.R(a.element,"click",this.dV);this.R(this.player,"presentingplayerstatechange",this.sQ);this.R(this.player,"appresize",this.Av);this.R(this.player,"fullscreentoggled",this.Av);this.Av();this.K=!0}0!=this.player.ni()&&g.BH.prototype.show.call(this);this.F.show();
this.player.kn("annotations_module")};
g.h.hide=function(){this.C&&(this.C.dispose(),this.C=void 0);g.BH.prototype.hide.call(this);this.player.app.L.o||(this.K&&this.F.hide(),this.player.Wk("annotations_module"))};
g.h.X=function(){this.C&&(this.C.dispose(),this.C=void 0);g.BH.prototype.X.call(this)};
g.h.PC=function(){this.player.Wd();this.player.ya("onCloseMiniplayer")};
g.h.dV=function(){this.player.ad()};
g.h.xE=function(a){if(a.target==this.G.element||a.target==this.D.element)g.$D("kevlar_miniplayer_scrim_pause")?2==this.player.ni()?this.player.ad():this.player.nd():this.player.ya("onExpandMiniplayer")};
g.h.aU=function(){g.U(this.player.getRootNode(),"ytp-player-minimized",this.player.app.L.o);this.player.app.L.o&&0==this.player.ni()?this.B.show():this.B.hide()};
g.h.rQ=function(){g.Ata(this.F);this.J.C();this.C.start()};
g.h.sQ=function(a){g.X(a.state,32)&&this.H.hide()};
g.h.Av=function(){var a=this.F,b=g.aU(this.player).Ua().width;a.Na=0;a.F=b;a.H=!1;g.pY(a)};
g.h.uX=function(a){this.player.app.L.o&&(0==a?(this.hide(),this.B.show()):(this.show(),this.B.hide()))};
g.h.Ob=function(){return this.H};
g.h.md=function(){return!1};
g.h.Jk=function(){return!1};
g.h.MF=function(){};
g.h.Vo=function(){};
g.h.Wo=function(){};
g.h.qn=function(){return null};
g.h.yv=function(){return new g.ih(0,0,0,0)};
g.h.zv=function(){};
g.h.Hq=function(a,b,c){a.style.left="";a.style.top="";a.style.bottom="";var d=g.Qh(a),e=g.aU(this.player).Ua().width;b&&["ytp-prev-button","ytp-next-button"].some(function(a){return g.zq(b,a)})?(c=12,a.style.top="12px"):(c-=d.width/2,a.style.bottom="25px");
a.style.left=g.ld(c,0,e-d.width)+"px"};
g.h.pq=function(){};
g.h.Bv=function(){};g.r(h6,g.EU);h6.prototype.init=function(){};
h6.prototype.load=function(){this.player.BC();this.o.show()};
h6.prototype.unload=function(){this.player.DC();this.o.hide()};g.BX.miniplayer=h6;})(_yt_player);
